const ML_LABEL_TRANSLATIONS: Record<string, string> = {
  almonds: 'badem',
  apple: 'elma',
  apple_pie: 'elmalı turta',
  artichoke_bottoms: 'enginar çanağı',
  avocado: 'avokado',
  banana: 'muz',
  baguette: 'baget ekmek',
  baklava: 'baklava',
  basil: 'fesleğen',
  beef_rib_steak: 'dana kaburga biftek',
  beans: 'fasulye',
  beef: 'dana eti',
  beetroot: 'pancar',
  bibimbap: 'bibimbap',
  bell_pepper: 'dolmalık biber',
  berries: 'orman meyveleri',
  bitter_gourd: 'acı kabak',
  boiled_egg: 'haşlanmış yumurta',
  black_chickpeas: 'siyah nohut',
  bok_choy: 'pak choi',
  bread: 'ekmek',
  broccoli: 'brokoli',
  brussels_sprouts: 'Brüksel lahanası',
  bulgur_pilaf: 'bulgur pilavı',
  burrito: 'burrito',
  butter: 'tereyağı',
  butter_chicken: 'tereyağlı tavuk',
  cabbage: 'lahana',
  caesar_salad: 'Sezar salatası',
  cake: 'kek',
  cannoli: 'kannoli',
  caprese_salad: 'Caprese salatası',
  carrot: 'havuç',
  carrot_cake: 'havuçlu kek',
  cashew: 'kaju',
  cauliflower: 'karnabahar',
  cheese: 'peynir',
  cheesecake: 'cheesecake',
  chicken: 'tavuk',
  chicken_curry: 'tavuk köri',
  chili: 'acı biber',
  chocolate_cake: 'çikolatalı kek',
  coriander: 'kişniş',
  corn: 'mısır',
  cucumber: 'salatalık',
  churros: 'churros',
  creme_brulee: 'krem brüle',
  croissant: 'kruvasan',
  cup_cakes: 'cupcake',
  dates: 'hurma',
  donut: 'donut',
  donuts: 'donut',
  egg: 'yumurta',
  egg_noodles: 'yumurtalı erişte',
  eggplant: 'patlıcan',
  eggs_benedict: 'eggs benedict',
  falafel: 'falafel',
  fish: 'balık',
  fish_and_chips: 'balık ve patates kızartması',
  flattened_rice: 'yassı pirinç',
  flour: 'un',
  garlic: 'sarımsak',
  ginger: 'zencefil',
  grapes: 'üzüm',
  french_fries: 'patates kızartması',
  french_onion_soup: 'Fransız soğan çorbası',
  french_toast: 'yumurtalı ekmek',
  fried_anchovies: 'hamsi tava',
  fried_calamari: 'kalamar tava',
  fried_rice: 'kızarmış pilav',
  garlic_bread: 'sarımsaklı ekmek',
  greek_salad: 'Yunan salatası',
  grilled_salmon: 'ızgara somon',
  hamburger: 'hamburger',
  hot_dog: 'sosisli sandviç',
  hummus: 'humus',
  ice_cream: 'dondurma',
  iskender_kebab: 'İskender kebap',
  kidney_beans: 'barbunya',
  kiwi: 'kivi',
  lasagna: 'lazanya',
  lemon: 'limon',
  lettuce: 'marul',
  macarons: 'makaron',
  mango: 'mango',
  meat_saute: 'et sote',
  melon: 'kavun',
  milk: 'süt',
  mushroom: 'mantar',
  moussaka: 'musakka',
  nachos: 'nachos',
  oats: 'yulaf',
  omelette: 'omlet',
  okra: 'bamya',
  onion: 'soğan',
  onion_rings: 'soğan halkası',
  orange: 'portakal',
  pad_thai: 'pad thai',
  paella: 'paella',
  pancakes: 'pankek',
  pasta: 'makarna',
  peach: 'şeftali',
  peanuts: 'yer fıstığı',
  pear: 'armut',
  peas: 'bezelye',
  pepper: 'biber',
  pho: 'pho',
  pizza: 'pizza',
  pineapple: 'ananas',
  pomegranate: 'nar',
  potato: 'patates',
  pretzel: 'pretzel',
  profiterole: 'profiterol',
  pumpkin: 'balkabağı',
  ramen: 'ramen',
  ravioli: 'ravioli',
  rice: 'pirinç',
  risotto: 'risotto',
  samosa: 'samosa',
  sashimi: 'sashimi',
  schnitzel: 'şinitzel',
  sea_bream: 'çipura',
  semolina: 'irmik',
  shepherds_salad: 'çoban salata',
  simit_turkish_bagel: 'simit',
  soup: 'çorba',
  spaghetti_bolognese: 'spagetti bolonez',
  spinach_stew: 'ıspanak yemeği',
  spring_rolls: 'börek rulo',
  steak: 'biftek',
  strawberry: 'çilek',
  strawberry_cake: 'çilekli kek',
  stuffed_bell_peppers: 'biber dolması',
  stuffed_grape_leaves: 'yaprak sarma',
  stuffed_meatballs: 'içli köfte',
  stuffed_white_cabbage: 'lahana sarması',
  sugar: 'şeker',
  sushi: 'sushi',
  sweet_potato: 'tatlı patates',
  tacos: 'taco',
  tiramisu: 'tiramisu',
  toast: 'tost',
  tomato: 'domates',
  tomato_soup: 'domates çorbası',
  turkish_delight: 'lokum',
  turkish_pastry: 'börek',
  turkish_ravioli: 'mantı',
  turkish_style_meatballs: 'köfte',
  tzatziki: 'cacık',
  waffles: 'waffle',
  watermelon: 'karpuz',
  white_bean_stew: 'kuru fasulye',
  zucchini_fritters: 'kabak mücveri',
};

function toReadableLabel(label: string): string {
  return label.replace(/_/g, ' ').trim();
}

function normalizeLabel(label: string): string {
  return label.trim().toLowerCase().replace(/\s+/g, '_');
}

function toTitleCase(label: string): string {
  return label
    .split(' ')
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(' ');
}

export function translateMlLabel(label: string): string {
  const normalized = normalizeLabel(label);
  const translated = ML_LABEL_TRANSLATIONS[normalized];
  if (translated) {
    return translated;
  }

  return toTitleCase(toReadableLabel(normalized));
}
